version: '3'
services:
  logger:
    build:
      context: fluentd
      dockerfile: Dockerfile
    container_name: fluentd
    volumes:
      - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf
    ports:
      - 5140:5140
      - 5140:5140/udp

  db:
    build: 
        context: ./db
        dockerfile: Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: abc@123
        MYSQL_DATABASE: localdb
    ports: 
        - 3306:3306 

networks:
  default:
