server:
  port: 8180

spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: my_group
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

containerization-tool:
  upload:
    directory: /home/vladtf/repos/containerization-tool/backend/target/upload
