server:
  port: 8180

spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: my_group
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: jdbc:mysql://localhost:3306/localdb?useSSL=false&serverTimezone=UTC
    username: root
    password: abc@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

containerization-tool:
  upload:
    directory: /home/vladtf/repos/containerization-tool/backend/target/upload # TODO: change this to relative path
