FROM ubuntu:20.04

# Set environment variable to non-interactive
ENV DEBIAN_FRONTEND=noninteractive

# Install basic tools
RUN apt-get update && \
    apt-get install -y iptables iproute2 iputils-ping net-tools tcpdump \
    vim git curl wget netcat traceroute dnsutils && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

