FROM containerization-tool-base-image:latest

# Install python3
RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY ./entrypoint.bin /usr/local/bin/entrypoint.py
RUN chmod +x /usr/local/bin/entrypoint.py

CMD ["/usr/bin/python3", "/usr/local/bin/entrypoint.py"]
